### ISSUE TITLE
"fileName" argument to Parser.Parse causes problems in the IDE

### ISSUE THREAD

**Issue by bmode** [SickheadGames/TinyPG#1]
First of all, thanks so much for putting this up on GitHub!  I just discovered TinyPG and it looks like a great tool.

I compared to the code from TinyPG 1.3 on CodeProject and your version on GitHub.  It looks like you added a new "string fileName" argument to the Parser.Parse methods in the C# templates.  This seems like a really good idea; however, it's causing problems in the TinyPG IDE.  When I push F5 (Generage&Run), I get an exception.

I traced the error down to line 157 in Compiler.cs:

```
object treeinstance = parsertype.InvokeMember("Parse", BindingFlags.InvokeMethod, null, parserinstance, new object[] { input });
```

The problem is that the parser no longer contains a .Parse method that only takes one parameter.  To get things working, I  added a dummy filename argument to line 157:

```
object treeinstance = parsertype.InvokeMember("Parse", BindingFlags.InvokeMethod, null, parserinstance, new object[] { input, "DummyFileName" });
```

I think a better solution though would be to add an overload for .Parse that only takes one parameter, the input string to parse.  A lot of people will probably use TinyPG to generate parsers for interactive use, where there is no filename.

Thanks again for your work on this project!

**Comment by tomspilman** [comment]
I actually didn't add an overload for `Parse()` because I wanted the caller aware that file name information is tracked thru the parser process.

I never use "Generate & Run" myself so I just missed that the IDE invokes the parser and wasn't passing the right parameters.

I'll submit a fix here in a second.

**Comment by bmode** [comment]
Great, thanks!

**Comment by tomspilman** [comment]
Should be fixed...

https://github.com/SickheadGames/TinyPG/commit/71b66e1492eebe9f55df796dc0ffb94e843fac05

... give it a try.

**Comment by bmode** [comment]
Yes, works perfectly now, thanks!  Looks like you also fixed the other issue I was having with the generated code not being compatible with the default CodeDom compiler.  I hacked my way around that by changing the target framework version from .Net 2.0 to .Net 4.0 before stumbling into the parser filename issue...

**Comment by tomspilman** [comment]
Cool...  closing this issue then.
