### ISSUE TITLE
problem with grammar

### ISSUE THREAD

**Issue by furesoft** [SickheadGames/TinyPG#26]
i have this Grammar: [Grammar](https://pastebin.com/z41UuXQK)

i have the problem that the code generator generates 2 same IDENTIFIER switch cases. When i delete the empty one it parses not correctly.

**Comment by nforndzi** [comment]
> i have this Grammar: [Grammar](https://pastebin.com/z41UuXQK)
> 
> i have the problem that the code generator generates 2 same IDENTIFIER switch cases. When i delete the empty one it parses not correctly.

TinyPG is an LL(1) parser generator, only one lookahead token is used to decide which production to parse. In your case more  than one lookahead token tokens are required.
